import Navbar from "@/components/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Task Food App",
  description: "Generated by create next app",
};

export default function ProductLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
    <div className=" min-h-screen flex-col">
      <div className="flex-1">{children}</div>
    </div>
    </>
  );
}
